import java.time.LocalDate
import java.time.format.DateTimeFormatter

plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.18'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
}

def dateFormat = DateTimeFormatter.ofPattern("yyyyMMdd")
def currentDate = LocalDate.now().format(dateFormat)

group = "org.example"
version = "1.0-SNAPSHOT-${currentDate}"

repositories {
    mavenCentral()
    maven {
        url = uri("https://nrgxnat.jfrog.io/artifactory/libs-release/")
    }
    maven {
        url = uri("https://raw.githubusercontent.com/DFKI-MLT/Maven-Repository/main/")
    }
    maven {
        url = uri("https://nexus.terrestris.de/repository/public/")
    }
    maven {
        url = uri("https://repo.spring.io/plugins-release/")
    }
    maven {
        url = uri("https://repo.gradle.org/gradle/libs-releases/")
    }
}

//TODO: Exclude .map files from build
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    //authentication
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'io.jsonwebtoken:jjwt:0.9.1'
    implementation 'org.springframework.boot:spring-boot-devtools'
    //text-to-speech-start
    implementation ('de.dfki.mary:voice-cmu-slt-hsmm:5.2.1') {
        exclude group: 'org.apache.logging.log4j'
    }
    implementation files('lib/voice-cmu-rms-hsmm-5.2.jar')
    implementation files('lib/voice-dfki-poppy-hsmm-5.2.jar')
    implementation 'com.google.cloud:google-cloud-texttospeech:2.55.0'
    //test-to-speech-end
    implementation 'com.h2database:h2'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'javax.validation:validation-api:2.0.1.Final'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'

}

test {
    useJUnitPlatform()
}